// This file was generated by counterfeiter
package httpserverfakes

import (
	"net/http"
	"sync"

	"github.com/tjarratt/go-best-practices/httpserver"
)

type FakeMiddleware struct {
	WrapStub        func(http.Handler) http.Handler
	wrapMutex       sync.RWMutex
	wrapArgsForCall []struct {
		arg1 http.Handler
	}
	wrapReturns struct {
		result1 http.Handler
	}
}

func (fake *FakeMiddleware) Wrap(arg1 http.Handler) http.Handler {
	fake.wrapMutex.Lock()
	fake.wrapArgsForCall = append(fake.wrapArgsForCall, struct {
		arg1 http.Handler
	}{arg1})
	fake.wrapMutex.Unlock()
	if fake.WrapStub != nil {
		return fake.WrapStub(arg1)
	} else {
		return fake.wrapReturns.result1
	}
}

func (fake *FakeMiddleware) WrapCallCount() int {
	fake.wrapMutex.RLock()
	defer fake.wrapMutex.RUnlock()
	return len(fake.wrapArgsForCall)
}

func (fake *FakeMiddleware) WrapArgsForCall(i int) http.Handler {
	fake.wrapMutex.RLock()
	defer fake.wrapMutex.RUnlock()
	return fake.wrapArgsForCall[i].arg1
}

func (fake *FakeMiddleware) WrapReturns(result1 http.Handler) {
	fake.WrapStub = nil
	fake.wrapReturns = struct {
		result1 http.Handler
	}{result1}
}

var _ httpserver.Middleware = new(FakeMiddleware)
